---
servers:
  pemserver:
    node_type: pemserver
    public_ip: 34.94.117.77
    private_ip: 10.0.0.2
  primary1:
    node_type: primary
    public_ip: 35.236.92.243
    private_ip: 10.0.0.5
    replication_type: asynchronous
    pem_agent: true
  standby2:
    node_type: standby
    public_ip: 34.94.18.198
    private_ip: 10.0.0.4
    replication_type: asynchronous
    pem_agent: true
  standby3:
    node_type: standby
    public_ip: 35.236.109.234
    private_ip: 10.0.0.3
    replication_type: asynchronous
    pem_agent: true
