---
servers:
  pemserver:
    node_type: pemserver
    public_ip: 52.149.1.177
    private_ip: 10.0.0.4
  primary1:
    node_type: primary
    public_ip: 52.191.188.219
    private_ip: 10.0.1.4
    replication_type: asynchronous
    pem_agent: true
  standby2:
    node_type: standby
    public_ip: 52.247.241.14
    private_ip: 10.0.2.4
    replication_type: asynchronous
    pem_agent: true
  standby3:
    node_type: standby
    public_ip: 52.175.201.17
    private_ip: 10.0.3.4
    replication_type: asynchronous
    pem_agent: true
