---
- hosts: localhost
  name: Configure Postgres or EPAS on Instances
  become: true
  gather_facts: no

  # When using collections
  collections:
      - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

  pre_tasks:
      - name: Initialize the user defined variables
        set_fact:
            os: "CentOS8"
            pg_version: 12
            pg_data: "/data/pgdata"
            pg_wal: "/data/pgwal"
            pg_type: "EPAS"
            yum_username: ""
            yum_password: ""
            use_hostname: yes
            pg_postgres_conf_params:
              - name: shared_buffers
                value: 4096MB
              - name: work_mem
                value: 32MB
              - name: maintenance_work_mem
                value: 420MB
              - name: huge_pages
                value: "off"
              - name: effective_cache_size
                value: 11GB
              - name: effective_io_concurrency
                value: 200

  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
    - setup_replication
    - manage_dbserver
    - setup_efm
    - setup_pem
    - pot_setup 
