---
- hosts: localhost
  name: Configure Postgres or EPAS on Instances
  become: true
  gather_facts: no

  # When using collections
  collections:
      - edb_devops.edb_postgres

  vars_files:
    - hosts.yml

  pre_tasks:
      - name: Initialize the user defined variables
        set_fact:
            os: "CentOS8"
            pg_version: 12
            pg_type: "PG"
            yum_username: ""
            yum_password: ""

  roles:
    - setup_repo
    - install_dbserver
    - init_dbserver
    - manage_dbserver
