---
#ansible-playbook --private-key=<id_rsa> R07_firewalld_stop.yml -u ec2-user -vv
- hosts: localhost
#  vars:
#    ansible_python_interpreter: /usr/bin/python2
  name: Stop Firewalld service on Remote Hosts
  #connection: local
  connection: ssh
  become: true
  gather_facts: no

  vars_files:
    - hosts.yml

  tasks:
    - name: Display current Node to Install
      block:
        - debug:
            msg: "Private IP = {{ item.value.private_ip }},
                Public IP = {{ item.value.public_ip }}"
          with_dict: "{{ servers }}"

    - name: Stop Firewalld Service in Each Node
      block:
        - name: Stop Firewalld Service
          service:
            name: firewalld
            state: stopped
            enabled: false
          delegate_to: "{{ item.value.public_ip }}"
          with_dict: "{{ servers }}"
