---
hosts:
  master:
    node_type: master
    private_ip1: 10.0.1.182
    private_ip2: 10.0.2.90
    private_ip3: 10.0.3.154
    public_ip: ec2-54-212-74-59.us-west-2.compute.amazonaws.com
    pgdbuser: postgres
    dbpassword: postgres
    replication_type: synchronous
    s3bucket: edb-postgres/wal
  standby1:
    node_type: standby
    private_ip1: 10.0.2.90
    private_ip2: 10.0.3.154
    public_ip: ec2-54-68-167-12.us-west-2.compute.amazonaws.com
    replication_user_password: postgres
    replication_type: synchronous
    s3bucket: edb-postgres/wal
  standby2:
    node_type: standby
    private_ip1: 10.0.2.90
    private_ip2: 10.0.3.154
    public_ip: ec2-34-221-140-51.us-west-2.compute.amazonaws.com
    replication_user_password: postgres
    replication_type: synchronous
    s3bucket: edb-postgres/wal
