---
hosts:
  master:
    node_type: master
    private_ip1: xxx.xxx.xxx
    private_ip2: xxx.xxx.xxx
    private_ip3: xxx.xxx.xxx
    public_ip: xxx.xxx.xxx
    pgdbuser: postgres
    dbpassword: postgres
    replication_type: synchronous
    s3bucket: xxx/wal
  standby1:
    node_type: standby
    private_ip1: xxx.xxx.xxx
    private_ip2: xxx.xxx.xxx
    public_ip: xxx.xxx.xxx
    replication_user_password: postgres
    replication_type: synchronous
    s3bucket: xxx/wal
  standby2:
    node_type: standby
    private_ip1: xxx.xxx.xxx
    private_ip2: xxx.xxx.xxx
    public_ip: xxx.xxx.xxx
    replication_user_password: postgres
    replication_type: synchronous
    s3bucket: xxx/wal
