---
hosts:
  master:
    node_type: master
    private_ip1: 172.31.73.229
    private_ip2: 172.31.8.227
    private_ip3: 172.31.43.212
    public_ip: 34.228.243.131
    pgdbuser: postgres
    dbpassword: postgres
    edbrepuser: edbrepuser
    replication_user_password: postgres
    replication_type: synchronous
    s3bucket: edb-arklog/walbackup
  standby1:
    node_type: standby
    private_ip1: 172.31.73.229
    private_ip2: 172.31.8.227
    public_ip: 3.235.132.71
  standby2:
    node_type: standby
    private_ip1: 172.31.73.229
    private_ip2: 172.31.43.212
    public_ip: 54.166.251.135
