---
hosts:
  master:
    node_type: master
    private_ip1: 172.31.85.148
    private_ip2: 172.31.84.127
    private_ip3: 172.31.92.219
    public_ip: 3.82.154.190
    pgdbuser: postgres
    dbpassword: postgres
    edbrepuser: edbrepuser
    replication_user_password: postgres
    replication_type: asynchronous
    s3bucket: edb-arklog/walbackup
  standby1:
    node_type: standby
    private_ip1: 172.31.85.148
    private_ip2: 172.31.84.127
    public_ip: 54.209.76.58
  standby2:
    node_type: standby
    private_ip1: 172.31.85.148
    private_ip2: 172.31.92.219
    public_ip: 184.72.98.44
