---
- hosts: localhost 
  name: Configure Postgres SQL Replication on Instances
  connection: local
  become: true
  gather_facts: yes
  #ignore_errors: yes
  
  vars_files:
    - /home/dortiz/hosts-dev.yml

  pre_tasks:
    - set_fact:
        OS: OS
        PG_VERSION: PG_VERSION
      with_dict: "{{ hosts }}"

  tasks:
    - name: Iterate through role with items from hosts file
      include_role:
        name: edb.postgres.replication
      with_dict: "{{ hosts }}"
