---
- name: Install Postgres SQL on Instances
  hosts: localhost
  connection: local
  gather_facts: yes
  #ignore_errors: yes
  
  vars_files:
    - hosts-demo.yml

  tasks:
    - name: Display current Node to Install
      block:
        - debug:
            msg: "Installing on Node Type = {{ item.value.node_type }}:
                Private IP = {{ item.value.private_ip }},
                Public IP = {{ item.value.public_ip }},
                User = {{ item.value.user }},
                SSH Private Key File = {{ item.value.ssh_private_key_file }},
                Operating System = {{ OS }}"
          with_dict: "{{ hosts }}"
      rescue:
        - debug:
            msg: "Error: When Installing a Node"
