#! /bin/bash
################################################################################
# Title           : deployment_main.sh making installs the required packages for
#                 : for deployment scripts
# Author          : Doug Ortiz and Co-authored by Vibhor Kumar
# Date            : Sept 7, 2020
# Version         : 1.0
################################################################################


################################################################################
# Quit on any error
set -e
# Verify any  undefined shell variables
set -u

################################################################################
# Source the common lib and config file
################################################################################
DIRECTORY=$(dirname $0)
if [[ "${DIRECTORY}" = "." ]]
then
   DIRECTORY="${PWD}"
fi
BASENAME=$(basename $0)
PLAYBOOK=${DIRECTORY}/playbook/playbook.yml
source ${DIRECTORY}/lib/common_funcs.sh
source ${DIRECTORY}/lib/config_funcs.sh
source ${DIRECTORY}/lib/pre_reqs_funcs.sh
source ${DIRECTORY}/lib/pg_install_funcs.sh
source ${DIRECTORY}/lib/usage_funcs.sh
source ${DIRECTORY}/lib/build_servers.sh

################################################################################
# Verify the arguments and call the config file
################################################################################
AWS_POSTGRES_INSTALL=""
AZURE_POSTGRES_INSTALL=""
GCLOUD_POSTGRES_INSTALL=""
AWS_SERVER=""
AZURE_SERVER=""
GCLOUD_SERVER=""
ARGUMENTS="$@"
ARGUMENTS="$(echo ${ARGUMENTS} | sed -e "s/  */ /g" \
                                     -e "s/^ *//g" \
                                     -e "s/ *$//g")"

verify_arguments ${ARGUMENTS}

if [[ "x${PROJECT_NAME}" = "x" ]] 
then
   read -r -e -p "Enter the project name: " PROJECT_NAME
   
   if [[ -z ${PROJECT_NAME} ]]
   then
       exit_on_error "Project name cannot be empty. Try again!"
   fi
fi

################################################################################
# Install the required packages
################################################################################
#install_gawk
#install_wget_curl
#install_terraform
#install_ansible

################################################################################
# Create resources based on the user input
################################################################################
if [[ "${AWS_SERVER}" = "create" ]]
then
    verify_aws
    
    aws_config_file "${PROJECT_NAME}"
    
    aws_build_server "${OSNAME}" \
                     "${REGION}" \
                     "${INSTANCE_COUNT}" \
                     "${PUB_FILE_PATH}" \
                     "${PEM_INSTANCE_COUNT}" \
                     "${PROJECT_NAME}" \
                     "${PRIV_FILE_PATH}" \
                    2>&1 | tee ${TERRAFORM_LOG}    

    cp -f ${DIRECTORY}/terraform/aws/hosts.yml ${DIRECTORY}/playbook/hosts.yml
fi

if [[ "${AZURE_SERVER}" = "create" ]]
then
    verify_azure
    
    azure_config_file "${PROJECT_NAME}"
   
    azure_build_server "${PUBLISHER}" \
                       "${OFFER}" \
                       "${SKU}" \
                       "${LOCATION}" \
                       "${INSTANCE_COUNT}" \
                       "${PUB_FILE_PATH}" \
                       "${PROJECT_NAME}" \
                       "${PEM_INSTANCE_COUNT}" \
                       "${PRIV_FILE_PATH}" \
                      2>&1 | tee ${TERRAFORM_LOG}

    cp -f ${DIRECTORY}/terraform/azure/hosts.yml ${DIRECTORY}/playbook/hosts.yml
fi

if [[ "${GCLOUD_SERVER}" = "create" ]]
then
    verify_gcloud
    
    gcloud_config_file "${PROJECT_NAME}"
   
    gcloud_build_server "${OSNAME}" \
                        "${SUBNETWORK_REGION}" \
                        "${INSTANCE_COUNT}" \
                        "${PUB_FILE_PATH}" \
                        "${PROJECT_ID}" \
                        "${PROJECT_NAME}" \
                        "${PEM_INSTANCE_COUNT}" \
                        "${CREDENTIALS_FILE_LOCATION}" \
                        "${PRIV_FILE_PATH}" \
                       2>&1 | tee ${TERRAFORM_LOG}

    cp -f ${DIRECTORY}/terraform/gcloud/hosts.yml ${DIRECTORY}/playbook/hosts.yml
fi

################################################################################
# Install Postgres based on the user input
################################################################################
if [[ "${AWS_POSTGRES_INSTALL}" = "install" ]]
then
    aws_config_file "${PROJECT_NAME}"
    
    aws_ansible_pg_install "${OSNAME}" \
                       "${PG_TYPE}" \
                       "${PG_VERSION}" \
                       "${YUM_USERNAME}" \
                       "${YUM_PASSWORD}" \
                       "${PRIV_FILE_PATH}" \
                       "${PEM_INSTANCE_COUNT}" | tee ${PG_INSTALL_LOG}
fi

if [[ "${AZURE_POSTGRES_INSTALL}" = "install" ]]
then
    azure_config_file "${PROJECT_NAME}"
    
    azure_ansible_pg_install "${PG_TYPE}" \
                       "${PG_VERSION}" \
                       "${YUM_USERNAME}" \
                       "${YUM_PASSWORD}" \
                       "${PUB_FILE_PATH}" \
                       "${PRIV_FILE_PATH}" \
                       "${PROJECT_NAME}" \
                       "${PEM_INSTANCE_COUNT}" | tee ${PG_INSTALL_LOG}
fi

if [[ "${GCLOUD_POSTGRES_INSTALL}" = "install" ]]
then
    gcloud_config_file "${PROJECT_NAME}"
    
    gcloud_ansible_pg_install "${PG_TYPE}" \
                       "${PG_VERSION}" \
                       "${YUM_USERNAME}" \
                       "${YUM_PASSWORD}" \
                       "${PUB_FILE_PATH}" \
                       "${PRIV_FILE_PATH}" \
                       "${PROJECT_NAME}" \
                       "${PEM_INSTANCE_COUNT}" | tee ${PG_INSTALL_LOG}
fi

################################################################################
# Destroy the Postgres deployment based on the user input
################################################################################
if [[ "${AWS_SERVER}" = "destroy" ]]
then
    aws_config_file "${PROJECT_NAME}"

    aws_destroy_server "${REGION}" | tee  ${TERRAFORM_LOG}
fi

if [[ "${AZURE_SERVER}" = "destroy" ]]
then
    azure_config_file "${PROJECT_NAME}"
    
    azure_destroy_server "${LOCATION}" | tee  ${TERRAFORM_LOG}
fi

if [[ "${GCLOUD_SERVER}" = "destroy" ]]
then
    gcloud_config_file "${PROJECT_NAME}"

    gcloud_destroy_server "${SUBNETWORK_REGION}" "${PROJECT_ID}" "${PUB_FILE_PATH}" | tee  ${TERRAFORM_LOG}
fi
