F_KEYPATH="~/.ssh/id_rsa.pub"    
F_PRIV_FILE_KEYPATH="~/.ssh/id_rsa"
F_PROJECTNAME="test"
F_PUB_KEYNAMEANDEXTENSION=""
F_PRIV_KEYNAMEANDEXTENSION=""

    F_PUB_KEYNAMEANDEXTENSION=$(echo "${F_KEYPATH##*/}")
    F_PRIV_KEYNAMEANDEXTENSION=$(echo "${F_PRIV_FILE_KEYPATH##*/}")
    F_NEW_PUB_KEYNAME="${F_PROJECTNAME}_${F_PUB_KEYNAMEANDEXTENSION}"
    F_NEW_PRIV_KEYNAME="${F_PROJECTNAME}_${F_PRIV_KEYNAMEANDEXTENSION}"

echo "${F_NEW_PUB_KEYNAME}"
echo "${F_NEW_PRIV_KEYNAME}"
