---
- name: Install Additional Packages
  yum:
    name: "{{ packages }}"
  vars:
    packages: 
      - wget
    state: present     
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Import Postgres Repo
  yum:
    #name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    name: "{{ postgresql_rpmrepo }}"
    state: present
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Disable SELINUX
  become: yes
  command: setenforce 0
  delegate_to: "{{ item.value.public_ip }}"

- name: Upgrade all yum packages
  yum:
    name: '*'
    state: latest
  delegate_to: "{{ item.value.public_ip }}"

- name: Install Postgres 10
  yum:
    name: "{{ packages }}"
  vars:
    packages: 
      - epel-release
      - postgresql10-server
      - postgresql10
    state: present     
  become: yes
  when: PG_VERSION == '10'
  delegate_to: "{{ item.value.public_ip }}"

- name: Install Postgres 11
  yum:
    name: "{{ packages }}"
  vars:
    packages: 
      - epel-release
      - postgresql11-server
      - postgresql11
    state: present     
  become: yes
  when: PG_VERSION == '11'
  delegate_to: "{{ item.value.public_ip }}"

- name: Install Postgres 12
  yum:
    name: "{{ packages }}"
  vars:
    packages: 
      - epel-release
      - postgresql12-server
      - postgresql12
    state: present     
  become: yes
  when: PG_VERSION == '12'
  delegate_to: "{{ item.value.public_ip }}"

- name: Install python pip
  yum:
    name: python-pip
    state: present    
  become: yes
  delegate_to: "{{ item.value.public_ip }}"
