---
servers:
  pemserver:
    node_type: pemserver
    public_dns: ec2-18-236-218-51.us-west-2.compute.amazonaws.com
    public_ip: 18.236.218.51
    private_ip: 10.0.2.51
  primary1:
    node_type: primary
    public_dns: ec2-34-222-149-123.us-west-2.compute.amazonaws.com
    public_ip: 34.222.149.123
    private_ip: 10.0.0.238
    replication_type: asynchronous
    pem_agent: true
  standby2:
    node_type: standby
    public_dns: ec2-34-221-76-186.us-west-2.compute.amazonaws.com
    public_ip: 34.221.76.186
    private_ip: 10.0.1.87
    replication_type: asynchronous
    pem_agent: true
  standby3:
    node_type: standby
    public_dns: ec2-34-223-67-131.us-west-2.compute.amazonaws.com
    public_ip: 34.223.67.131
    private_ip: 10.0.3.42
    replication_type: asynchronous
    pem_agent: true
