---
- hosts: localhost 
  name: Execute SQL Statements on Postgres SQL Cluster
  connection: local
  become: true
  gather_facts: yes
  #ignore_errors: yes
  
  vars_files:
    - /home/dortiz/hosts-sql.yml

  pre_tasks:
    - set_fact:
        OS: OS
        PG_VERSION: PG_VERSION
      with_dict: "{{ hosts }}"

  tasks:
    - name: Iterate through role with items from hosts file
      include_role:
        name: edb.postgres.sqlexec
      with_dict: "{{ hosts }}"
