---
   
   - name: Create pgpass file
     lineinfile:
         path: /var/lib/edb/.pgpass
         line: "*:5444:*:edbrepuser:{{ REPLICATION_USER_PASSWORD }}"
         create: yes
         owner: enterprisedb
         group: enterprisedb
         mode: '0600'
     become: yes

   - name: Stop DB service
     systemd:
        name: edb-as-12
        state: stopped
     become: yes

   - name: Delete data directory
     file:
        path: /var/lib/edb/as12/data
        state: absent
     become: yes
 
   - name: Take pgbase back-up
     shell: PGPASSWORD="{{ REPLICATION_USER_PASSWORD }}" /usr/edb/as12/bin/pg_basebackup -R -D /var/lib/edb/as12/data --host={{ ip1 }} --port=5444 --username=edbrepuser
     become: yes

   - name: Change permission of data directory
     file:
       path: /var/lib/edb/as12/data
       state: directory
       owner: enterprisedb
       group: enterprisedb
       recurse: yes
     become: yes
  
   - name: Modify paramter in postgresql.conf file
     lineinfile:
         path: /var/lib/edb/as12/data/postgresql.conf
         regexp: "{{item.From}}"
         line: "{{item.To}}"
     with_items:
       - { From: "^#promote_trigger_file = ''", To: "promote_trigger_file = '/var/lib/edb/as12/data/waltrigger'" }
       - { From: "^#restore_command = ''", To: "restore_command = 'cp /backup/%f %p'" }
       - { From: "#recovery_target_timeline = 'latest'", To: "recovery_target_timeline = 'latest'" }
     become: yes

   
   - name: Modify paramter in postgresql.conf file if synchronous replication
     shell: | 
         sed -i "s@#primary_conninfo = ''@primary_conninfo = 'user=edbrepuser password={{ REPLICATION_USER_PASSWORD }} host={{ ip1 }} port=5444 sslmode=prefer sslcompression=0 gssencmode=prefer krbsrvname=postgres target_session_attrs=any application_name=slave1'@g" /var/lib/edb/as12/data/postgresql.conf
         sed -i -e 's/target_session_attrs=any/& application_name=slave3/' /var/lib/edb/as12/data/postgresql.auto.conf 
     become: yes
     when: REPLICATION_TYPE == 'synchronous'

   - name: Add entry in pg_hba file
     lineinfile:
         path: /var/lib/edb/as12/data/pg_hba.conf
         line: host replication edbrepuser {{ ip2 }}/32 md5
     become: yes

   - name: Add entry in pg_hba file
     lineinfile:
         path: /var/lib/edb/as12/data/pg_hba.conf
         line: host replication edbrepuser {{ ip3 }}/32 md5
     become: yes

   
   - name: Start DB process
     systemd:
        name: edb-as-12
        state: restarted
     become: yes


