---
hosts:
  master:
    node_type: master
    public_ip: ec2-50-112-214-245.us-west-2.compute.amazonaws.com
  standby1:
    node_type: standby
    public_ip: ec2-54-203-164-165.us-west-2.compute.amazonaws.com
  standby2:
    node_type: standby
    public_ip: ec2-54-191-165-245.us-west-2.compute.amazonaws.com
