---
hosts:
  master:
    node_type: master
    public_ip: ec2-35-155-66-220.us-west-2.compute.amazonaws.com
  standby1:
    node_type: standby
    public_ip: ec2-34-221-133-208.us-west-2.compute.amazonaws.com
  standby2:
    node_type: standby
    public_ip: ec2-54-184-155-162.us-west-2.compute.amazonaws.com
