---
hosts:
  master:
    node_type: master
    public_ip: ec2-54-212-74-59.us-west-2.compute.amazonaws.com
  standby1:
    node_type: standby
    public_ip: ec2-54-68-167-12.us-west-2.compute.amazonaws.com
  standby2:
    node_type: standby
    public_ip: ec2-34-221-140-51.us-west-2.compute.amazonaws.com
