---
hosts:
  master:
    node_type: master
    public_ip: 3.231.244.6 
  standby1:
    node_type: standby
    public_ip: 3.219.168.237
  standby2:
    node_type: standby
    public_ip: 54.210.219.181
