---
servers:
  pemserver:
    node_type: pemserver
    public_dns: ec2-34-222-170-188.us-west-2.compute.amazonaws.com
    public_ip: 34.222.170.188
    private_ip: 10.0.2.19
  primary1:
    node_type: primary
    public_dns: ec2-54-186-149-203.us-west-2.compute.amazonaws.com
    public_ip: 54.186.149.203
    private_ip: 10.0.0.154
    replication_type: asynchronous
    pem_agent: true
  standby2:
    node_type: standby
    public_dns: ec2-34-220-80-230.us-west-2.compute.amazonaws.com
    public_ip: 34.220.80.230
    private_ip: 10.0.1.218
    replication_type: asynchronous
    pem_agent: true
  standby3:
    node_type: standby
    public_dns: ec2-44-235-74-131.us-west-2.compute.amazonaws.com
    public_ip: 44.235.74.131
    private_ip: 10.0.3.43
    replication_type: asynchronous
    pem_agent: true
