# Location
variable "azure_location" {
  type = string
  # Examples: centralus, eastus, eastus2, westus, westcentralus, westus2, northcentralus, southcentralus
  default = "westus2"
}

variable "vnet_cidr_block" {
  description = "CIDR Block for the VNet"
  default     = "10.0.0.0/16"
}

# Name of the Cluster
variable "cluster_name" {
  description = "The name to the cluster"
  default     = "tclusterEDB"
  type        = string
}

variable "ssh_key_path" {
  type = string
  # Utilize the id_rsa.pub generated by keygen
  # Example: "~/.ssh/id_rsa.pub"
  default = ""
}

# Instance Size
variable "instance_size" {
  default = "Standard_A1"
}

# Count
variable "instance_count" {
  default = 1
}


# PEM Instance Count
variable "pem_instance_count" {
  default = 0
}

# Synchronicity
variable "synchronicity" {
  default = "asynchronous"
}

# Operating Systems Supported
# CentOS7
# publisher = "OpenLogic"
# offer     = "Centos"
# sku       = "7.7"
# RHEL7
# publisher = "RedHat"
# offer     = "RHEL"
# sku       = "7.8"
variable publisher {
  default = "OpenLogic"
  #default = "RedHat"
}

variable offer {
  default = "Centos"
  #default = "RHEL"
}

variable sku {
  default = "7.7"
  #default = "7.8"
}

variable admin_username {
  default = "centos"
}

# Ansible Inventory Filenames
# Ansible Yaml Inventory Filename
variable "ansible_inventory_yaml_filename" {
  default = "inventory.yml"
}

# Ansible Yaml PEM Inventory Filename
variable "ansible_pem_inventory_yaml_filename" {
  default = "pem-inventory.yml"
}

# Ansible Ini Inventory Filename
variable "ansible_inventory_ini_filename" {
  default = "inventory"
}

# OS CSV Filename
variable "os_csv_filename" {
  default = "os.csv"
}

# Ansible Add Hosts Filename
variable "add_hosts_filename" {
  type    = string
  default = "add_host.sh"
}
