# Tags
variable "project_tags" {
  description = "A map of tags to add to all resources."
  type        = map(string)
  default = {
    key = "EDB_PREREQS_AZURE"
  }
}

variable "project_tag" {
  type    = string
  default = "EDB_PREREQS_AZURE_DEPLOYMENT"
}

# Location
variable "azure_location" {
  type    = string
  default = "westus2"
}

# Storage
variable "storageaccount_name" {
  description = "Name of the bucket for storing related data of deployment"
  type        = string
  default     = "edbpostgres"
}

variable "storagecontainer_name" {
  description = "Name of the bucket for storing related data of deployment"
  type        = string
  default     = "edbprereqsstoragecontainer"
}

# VNet
variable "vnet_name" {
  type    = string
  default = "EDB-PREREQS-VNet"
}

variable "vnet_cidr_block" {
  description = "CIDR Block for the VNet"
  default     = "10.0.0.0/16"
}

# Resource Group
variable "resourcegroup_tag" {
  default = "EDB-PREREQS-RESOURCEGROUP"
}

variable "resourcegroup_name" {
  default = "EDB-PREREQS-RESOURCEGROUP"
}

# Subnets
variable "subnet_name" {
  default = "EDB-PREREQS-PUBLIC-SUBNET"
}

variable "subnet_tag" {
  default = "EDB-PREREQS-PUBLIC-SUBNET"
}

# Security Group
variable "securitygroup_name" {
  default = "EDB-PREREQS-SECURITYGROUP"
}

variable "ssh_key_path" {
  type = string
  # Utilize the id_rsa.pub generated by keygen
  default = "~/.ssh/id_rsa.pub"
}

# Count
variable "instance_count" {
  default = 1
}

# Operating Systems Supported
# CentOS7
# publisher = "OpenLogic"
# offer     = "Centos"
# sku       = "7.7"
# RHEL7
# publisher = "RedHat"
# offer     = "RHEL"
# sku       = "7.8"
variable publisher {
  default = "OpenLogic"
  #default = "RedHat"
}

variable offer {
  default = "Centos"
  #default = "RHEL"
}

variable sku {
  default = "7.7"
  #default = "7.8"
}
