- hosts: all

   tasks:

    - name: Install Database for DBengine 10
      include: installpg10.yml 
      when: DB_ENGINE == 'pg10'
     
    - name: Install Database DBengine pg11
      include: installpg11.yml 
      when: DB_ENGINE == 'pg11'

    - name: Install Database for DBengine pg12
      include: installpg12.yml 
      when: DB_ENGINE == 'pg12'

    - name: Install Database  for DBengine epas10
      include: installepas10.yml 
      when: DB_ENGINE == 'epas10'
     
    - name: Install Database for DBengine epas11
      include: installepas11.yml
      when: DB_ENGINE == 'epas11'

    - name: Install Database for DBengine epas12
      include: installepas12.yml
      when: DB_ENGINE == 'epas12'

         
 - hosts: "{{ MASTER }}"
    
   tasks:

    - name: Configure master for DBengine pg10
      include: configuremasterpg10.yml 
      when: DB_ENGINE == 'pg10'
     
    - name: Configure master for DBengine pg11
      include: configuremasterpg11.yml 
      when: DB_ENGINE == 'pg11'

    - name: Configure master for DBengine pg12
      include: configuremasterpg12.yml 
      when: DB_ENGINE == 'pg12'

    - name: Configure master for DBengine epas10
      include: configuremasterepas10.yml 
      when: DB_ENGINE == 'epas10'
     
    - name: Configure master for DBengine epas11
      include: configuremasterepas11.yml
      when: DB_ENGINE == 'epas11'

    - name: Configure master for DBengine epas12
      include: configuremasterepas12.yml
      when: DB_ENGINE == 'epas12'

  

 - hosts: "{{ SLAVE1 }}"
   
   tasks:
     
    - name: Configure slave for DBengine pg10
      include: configureslavepg10.yml 
      when: DB_ENGINE == 'pg10' 
     
    - name: Configure slave for DBengine pg11
      include: configureslavepg11.yml 
      when: DB_ENGINE == 'pg11' 

    - name: Configure slave for DBengine pg12
      include: configureslavepg12.yml 
      when: DB_ENGINE == 'pg12' 

    - name: Configure slave for DBengine epas10
      include: configureslaveepas10.yml 
      when: DB_ENGINE == 'epas10' 
     
    - name: Configure slave for DBengine epas11
      include: configureslaveepas11.yml
      when: DB_ENGINE == 'epas11' 

    - name: Configure slave for DBengine epas12
      include: configureslaveepas12.yml
      when: DB_ENGINE == 'epas12' 

 - hosts: "{{ SLAVE2 }}"
   
   tasks:

    - name: Configure slave for DBengine pg10
      include: configureslavepg10.yml
      when: DB_ENGINE == 'pg10' 

    - name: Configure slave for DBengine pg11
      include: configureslavepg11.yml
      when: DB_ENGINE == 'pg11' 

    - name: Configure slave for DBengine pg12
      include: configureslavepg12.yml
      when: DB_ENGINE == 'pg12' 

    - name: Configure slave for DBengine epas10
      include: configureslaveepas10.yml
      when: DB_ENGINE == 'epas10' 

    - name: Configure slave for DBengine epas11
      include: configureslaveepas11.yml
      when: DB_ENGINE == 'epas11'

    - name: Configure slave for DBengine epas12
      include: configureslaveepas12.yml
      when: DB_ENGINE == 'epas12'             

 - hosts: "{{ MASTER }}"

   tasks:

    
    - name: Change in postgresql.conf file
      lineinfile:
          path: /var/lib/edb/as10/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave1,slave2)'
      become: yes
      run_once: true
      when: DB_ENGINE == 'epas10' and REPLICATION_TYPE == 'synchronous' 
       
  
    - name: Restart DB service
      systemd:
          name: edb-as-10
          state: restarted
      become: yes
      run_once: true
      when: DB_ENGINE == 'epas10'  and REPLICATION_TYPE == 'synchronous' 

    - name: Change in postgresql.conf file
      lineinfile:
          path: /var/lib/edb/as11/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave1,slave2)'
      become: yes
      run_once: true 
      when: DB_ENGINE == 'epas11' and REPLICATION_TYPE == 'synchronous' 
       
  
    - name: Restart DB service
      systemd:
          name: edb-as-11
          state: restarted
      become: yes
      run_once: true
      when: DB_ENGINE == 'epas11' and REPLICATION_TYPE == 'synchronous' 


    - name: Change in postgresql.conf file
      lineinfile:
          path: /var/lib/edb/as12/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave1,slave2)'
      become: yes
      run_once: true
      when: DB_ENGINE == 'epas12' and REPLICATION_TYPE == 'synchronous' 
       
  
    - name: Restart DB service
      systemd:
          name: edb-as-12
          state: restarted
      become: yes
      run_once: true
      when: DB_ENGINE == 'epas12' and REPLICATION_TYPE == 'synchronous' 

    - name: Change in postgresql.conf file
      lineinfile:
          path: /var/lib/pgsql/10/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave1,slave2)'
      become: yes
      run_once: true
      when: DB_ENGINE == 'pg10' and REPLICATION_TYPE == 'synchronous' 
       
  
    - name: Restart DB service
      systemd:
          name: postgresql-10
          state: restarted
      become: yes
      run_once: true
      when: DB_ENGINE == 'pg10' and REPLICATION_TYPE == 'synchronous' 

    - name: Change in postgresql.conf file 
      lineinfile:
          path: /var/lib/pgsql/11/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave1,slave2)'
      become: yes
      run_once: true
      when: DB_ENGINE == 'pg11' and REPLICATION_TYPE == 'synchronous'
       
  
    - name: Restart DB service
      systemd:
          name: postgresql-11
          state: restarted
      become: yes
      run_once: true
      when: DB_ENGINE == 'pg11' and REPLICATION_TYPE == 'synchronous' 

    - name: Change in postgresql.conf file
      lineinfile:
          path: /var/lib/pgsql/12/data/postgresql.conf
          regexp: "^#synchronous_standby_names = .*"
          line: synchronous_standby_names = 'any 1 (slave1,slave2)'
      become: yes
      run_once: true
      when: DB_ENGINE == 'pg12' and REPLICATION_TYPE == 'synchronous' 
       
  
    - name: Restart DB service
      systemd:
          name: postgresql-12
          state: restarted
      become: yes
      run_once: true
      when: DB_ENGINE == 'pg12' and REPLICATION_TYPE == 'synchronous'    

