---
# Tasks file for edb.postgres.install Role

# Configure Variables
- name: Display details of Node to Configure
  block:
    - debug:
        msg: 
            "Operating System = {{ OS }}:
             Postgres Version = {{ PG_VERSION }},
             Node Type = {{ item.value.node_type }},
             Public IP = {{ item.value.public_ip }}"

# Setting variables available in all nodes
- name: Set Node Type
  set_fact:
    NODE_TYPE: "{{ item.value.node_type }}"
  register: output

- name: Set Private IP 1
  set_fact:
    PRIVATE_IP1: "{{ item.value.private_ip1}}"
  register: output

- name: Set Private IP 2
  set_fact:
    PRIVATE_IP2: "{{ item.value.private_ip2}}"
  register: output

- name: SEt Public IP Address
  set_fact:
    PUBLIC_IP: "{{ item.value.public_ip}}"
  register: output

# Setting variables available only on master
- name: Set PGDBUSER
  set_fact:
    PGDBUSER: "{{ item.value.pgdbuser}}"
  register: output
  when: item.value.node_type == 'master'

- name: Set DBPASSWORD
  set_fact:
    DBPASSWORD: "{{ item.value.dbpassword }}"
  register: output
  when: item.value.node_type == 'master'

- name: Set EDBREPUSER
  set_fact:
    EDBREPUSER: "{{ item.value.edbrepuser }}"
  register: output
  when: item.value.node_type == 'master'

- name: Set REPLICATION_USER_PASSWORD
  set_fact:
    REPLICATION_USER_PASSWORD: "{{ item.value.replication_user_password }}"
  register: output
  when: item.value.node_type == 'master'

- name: Set REPLICATION_TYPE
  set_fact:
    REPLICATION_TYPE: "{{ item.value.replication_type }}"
  register: output
  when: item.value.node_type == 'master'

- name: Set S3 Bucket
  set_fact:
    S3BUCKET: "{{ item.value.s3bucket }}"
  register: output
  when: item.value.node_type == 'master'

# Postgres12 Master and Standby
- include_tasks: setup-CentOS7P12Master.yml
  #when: ansible_os_family == 'Debian'
  when: OS == 'CentOS7' and PG_VERSION == '12' and item.value.node_type == 'master'

- include_tasks: setup-CentOS7P12Standby.yml
  #when: ansible_os_family == 'Debian'
  when: OS == 'CentOS7' and PG_VERSION == '12' and item.value.node_type == 'standby'
