---
# Standby configuration settings

# Display details of Node being configured
- name: Display Details of Standby Node to Configure
  block:
    - debug:
        msg: 
            "Operating System = {{ OS }}:
             Postgres Version = {{ PG_VERSION }},
             Node Type = {{ item.value.node_type }},
             Public IP = {{ item.value.public_ip }},
             S3BUCKET = {{ S3BUCKET }},
             PUBLIC_IP = {{ PUBLIC_IP }},
             EDBREPUSER = {{ EDBREPUSER }},
             REPLICATION_TYPE = {{ REPLICATION_TYPE }},
             REPLICATION_USER_PASSWORD = {{ REPLICATION_USER_PASSWORD }},
             Private IP 1 = {{ item.value.private_ip1 }},
             Private IP 2 = {{ item.value.private_ip2 }},
             PRIVATE_IP1 = {{ PRIVATE_IP1 }},
             PRIVATE_IP2 = {{ PRIVATE_IP2 }},
             POSTGRES10 BIN FOLDER = {{ POSTGRES10_BIN_FOLDER }},
             POSTGRES10 DATA FOLDER = {{ POSTGRES10_DATA_FOLDER }}"

- name: Create pgpass file
  lineinfile:
    path: "{{ POSTGRES10_PGPASS_FOLDER_AND_FILE }}"
    line: "*:{{ REPLICATION_PORT }}:*:{{ EDBREPUSER }}:{{ REPLICATION_USER_PASSWORD }}"
    create: yes
    owner: "{{ PGDBUSER }}" 
    group: "{{ PGDBUSER }}"
    mode: '0600'
  become: yes
  delegate_to: "{{ PUBLIC_IP }}"

- name: Stop Postgres Database Service
  shell: |
    systemctl stop postgresql-10.service
  become: yes
  delegate_to: "{{ item.value.public_ip }}"
                                                                                                                 
- name: Initialize Postgres Data Folder
  file:
    path: "{{ POSTGRES10_DATA_FOLDER }}"
    state: absent
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Perform pgbase back-up
  shell: |
    PGPASSWORD="{{ REPLICATION_USER_PASSWORD }}" {{ POSTGRES10_BIN_FOLDER }}pg_basebackup -R -D {{ POSTGRES10_DATA_FOLDER }} --host={{ item.value.private_ip1 }} --port={{ REPLICATION_PORT }} --username={{ EDBREPUSER }}
  become: yes
  delegate_to: "{{ item.value.public_ip }}"

- name: Change Permissions of Data Folder
  file:
    path: "{{ POSTGRES10_DATA_FOLDER }}"
    state: directory
    owner: "{{ PGDBUSER }}"
    group: "{{ PGDBUSER }}"
    recurse: yes
  become: yes
  delegate_to: "{{ item.value.public_ip }}"


- name: Create recovery.conf file
  blockinfile:
         path: "{{ POSTGRES10_DATA_FOLDER }}recovery.conf"
         owner: "{{ PGDBUSER }}"
         group: "{{ PGDBUSER }}"
         block: |
           trigger_file = '{{ POSTGRES10_DATA_FOLDER }}waltrigger'
           restore_command = 'aws s3 cp s3://{{ S3BUCKET }}/%f %p'
           recovery_target_timeline = 'latest'
  become: yes
  delegate_to: "{{ PUBLIC_IP }}"

- name: Configure Replication Parameters in postgresql.conf file
  shell: sed -i -e 's/target_session_attrs=any/& application_name=slave1/' "{{ POSTGRES10_DATA_FOLDER }}recovery.conf" 
  become: yes
  when: REPLICATION_TYPE == 'synchronous' and item.key == 'standby1'
  delegate_to: "{{ PUBLIC_IP }}"

- name: Configure Replication Connection Parameters in postgresql.conf file
  shell: sed -i -e 's/target_session_attrs=any/& application_name=slave2/' "{{ POSTGRES10_DATA_FOLDER }}recovery.conf"
  become: yes
  when: REPLICATION_TYPE == 'synchronous' and item.key == 'standby2'
  delegate_to: "{{ item.value.public_ip }}"

- name: Add Replication IP Address 1 Entry to pg_hba Configuration File
  lineinfile:
    path: "{{ POSTGRES10_DATA_FOLDER }}pg_hba.conf"
    line: host replication {{ EDBREPUSER }} {{ PRIVATE_IP2 }}/32 md5
  become: yes
  delegate_to: "{{ PUBLIC_IP }}"

- name: Add Replication IP Address 2 Entry to pg_hba Configuration File
  lineinfile:
    path: "{{ POSTGRES10_DATA_FOLDER}}pg_hba.conf"
    line: host replication {{ EDBREPUSER }} {{ PRIVATE_IP1 }}/32 md5
  become: yes
  delegate_to: "{{ PUBLIC_IP }}"

- name: Wait for 10 seconds
  wait_for:
    timeout: 10
  delegate_to: "{{ PUBLIC_IP }}"

- name: Restart DB service
  shell: |
    systemctl restart postgresql-10.service
  become: yes
  delegate_to: "{{ item.value.public_ip }}"
