---

- name: Add pg_project_user hba local entry
  set_fact:
    pg_pot_local_hba:
      - user: "{{ pg_project_user }},{{pg_owner }}"
        source: "127.0.0.1/32"
        databases: "edb"

- name: Merge all the entry
  set_fact:
    pg_allow_ip_addresses: "{{ pg_allow_ip_addresses + pg_pot_local_hba }}"

- name: Update hba config
  include_role:
    name: edb_devops.edb_postgres.manage_dbserver
    tasks_from: manage_hba_conf
  vars:
    pg_hba_ip_addresses: "{{ pg_allow_ip_addresses }}"

