---
- name: Set pem_server_private_ip, pem_server_public_ip
  set_fact:
    pem_server_public_ip: "{{ item.value.public_ip }}"
    pem_server_private_ip: "{{ item.value.private_ip }}"
    primary_server_public_ip: "{{ item.value.public_ip }}"
  when: item.value.node_type == 'pemserver'

- name: Set primary_server_ip
  set_fact:
    primary_public_ip: "{{ item.value.public_ip }}"
  when: item.value.node_type == 'primary'

- name: Prepare the list
  set_fact:
    temp_list:
       - users: "{{ pg_project_user }}, {{ pg_owner }}"
         source: "{{ item.value.private_ip }}/32"
         databases: edb

- name: Prepare array of list
  set_fact:
    pg_allow_ip_addresses: "{{ pg_allow_ip_addresses + [temp_list] }}"
